SoloCapstoneProject/Models/Provider.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SoloCapstoneProject.Models
{
    public class Provider
    {

        [Key]
        public int ProviderId { get; set; }
        [DisplayName("First Name")]
        public string FirstName { get; set; }
        [DisplayName("Last Name")]
        public string LastName { get; set; }
        [DisplayName("Phone Number")]
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Services { get; set; }
        public double Rating { get; set; }

        [ForeignKey("IdentityUser")]
        [DisplayName("User Id")]
        public string IdentityUserId { get; set; }
        public IdentityUser IdentityUser { get; set; }



    }
}

SoloCapstoneProject/Models/Providers.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SoloCapstoneProject.Models
{
    public class Providers
    {

        [Key]
        public int ProviderId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Zipcode { get; set; }

        [ForeignKey("IdentityUser")]
        public string IdentityUserId { get; set; }
        public IdentityUser IdentityUser { get; set; }


    }
}

SoloCapstoneProject/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SoloCapstoneProject.Contracts;
using SoloCapstoneProject.Data;
using SoloCapstoneProject.Models;
using SQLitePCL;
using SendGrid;
using SendGrid.Helpers.Mail;

namespace SoloCapstoneProject.Controllers
{
    public class OrdersController : Controller
    {

        private readonly ApplicationDbContext _context;
        private IRepositoryWrapper _repo;

        public OrdersController(ApplicationDbContext context, IRepositoryWrapper repo)
        {
            _context = context;
            _repo = repo;
        }

        // GET: OrdersController
        public ActionResult Index()
        {

            return View();
        }

        // GET: OrdersController/Details/5
        public ActionResult ConsumerDetails()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundConsumer = _context.Consumers.Where(f => f.IdentityUserId == userId).SingleOrDefault();

            return View(foundConsumer);

        }

        // GET: OrdersController/Create
        public ActionResult Create(int id)
        {

            return View();
        }

        // POST: OrdersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Order order)
        {


            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundConsumer = _context.Consumers.Where(f => f.IdentityUserId == userId).SingleOrDefault();
            var foundProvider = _context.Providers.Where(p => p.ProviderId == 4).SingleOrDefault();
            order.ConsumerId = foundConsumer.ConsumerId;
            order.ProviderId = 4;

            _context.Add(order);
            _repo.Order.Save();


            return View("OrderReview", order);

        }

        public ActionResult OrderReview()
        {
            return View();
        }

        // GET: OrdersController/Edit/5
        public async Task<IActionResult> ConsumerEdit(int? id)
        {
            
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);

            if (order == null)
            {
                return NotFound();
            }

            return View(order);

        }

        // POST: OrdersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ConsumerEdit(int id, Order order)
        {

            var foundOldOrder = _context.Orders.Where(o => o.OrderId == id).SingleOrDefault();
            foundOldOrder.ServiceDate = order.ServiceDate;
            foundOldOrder.ConsumerComments = order.ConsumerComments;
            foundOldOrder.ProviderComments = order.ProviderComments;

            
            try
            {
                return RedirectToAction("Details",foundOldOrder);
            }
            catch
            {
                return View();
            }
        }

        // GET: OrdersController/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
                      
            if (id == null)
            {
                return NotFound();
            }

            var order = _context.Orders.Where(o => o.OrderId == id).SingleOrDefault();

            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: OrdersController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {

            Order order = _context.Orders.Where(o=>o.OrderId == id).SingleOrDefault();
            _context.Orders.Remove(order);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));

        }

        public ActionResult ConsumerRequest(int id)
        {

            var newOrder = _context.Orders.Where(o => o.OrderId == id).SingleOrDefault();
            var matchingConsumer = _context.Orders.Where(c => c.ConsumerId == newOrder.ConsumerId);

            return View(matchingConsumer);
        }

        public ActionResult ProviderRequest(int id)
        {

            var matchingProvider = _context.Orders.Where(p => p.ProviderId == id);
            return View(matchingProvider);
        }

        public ActionResult ProvRequestDetails(int id)
        {

            var order = _context.Orders.Where(o => o.OrderId == id).SingleOrDefault();
            return View(order);

        }

        public async Task<ActionResult> ConfirmedAppointment(int id)
        {
            var order = _context.Orders.Where(c => c.OrderId == id).SingleOrDefault();
            order.isAppointConfirmed = true;
            _context.SaveChanges();
            Execute();

            return View("ProvRequestDetails", order);

        }


        static async Task Execute()
        {
            var apiKey = "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"; 
            var client = new SendGridClient(apiKey);
            var from = new EmailAddress("chouac1@gmail.com", "Choua Cha");
            var subject = "Your appointment has been confirmed!";
            var to = new EmailAddress("marylamb007.business@gmail.com", "Gawn Service User");
            var plainTextContent = "Click for more details!";
            var htmlContent = "<strong>Your appointment has been confirmed! The next thing you might want to do is get in contact with the provider and give him some details or any specifics that you might need! Thanks for using Gawn Services!</strong>";
            var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
            var response = await client.SendEmailAsync(msg);
        }

        public async Task<IActionResult> ProviderEdit(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);

            if (order == null)
            {
                return NotFound();
            }

            return View(order);

        }

        public ActionResult ProviderEdit(int id)
        {
            Order order = new Order();
            var foundOldOrder = _context.Orders.Where(o => o.OrderId == id).SingleOrDefault();
            foundOldOrder.ProviderComments = order.ProviderComments;

            try
            {
                return RedirectToAction("ProvRequestDetails", foundOldOrder);
            }
            catch
            {
                return View();
            }

        }
    }
}

SoloCapstoneProject/Controllers/ProvidersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SoloCapstoneProject.Contracts;
using SoloCapstoneProject.Data;
using SoloCapstoneProject.Models;
using SoloCapstoneProject.Services;

namespace SoloCapstoneProject.Controllers
{
    public class ProvidersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private IRepositoryWrapper _repo;

        public ProvidersController(ApplicationDbContext context, IRepositoryWrapper repo)
        {
            _context = context;
            _repo = repo;
        }

        [Authorize(Roles = "Provider")]

        // GET: Providers
        public async Task<IActionResult> Index()
        {

            return RedirectToAction("Dashboard");
        }

        public async Task<IActionResult> Dashboard(int? id)
        {

            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundProvider = _context.Providers.Where(i => i.IdentityUserId == userId).SingleOrDefault();


            if (foundProvider == null)
            {
                return RedirectToAction("Create");
            }

            return View(foundProvider);
        }


        public async Task<IActionResult> ListOfProviders(string searchString)
        {
            var providers = from m in _context.Providers
                            select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                providers = providers.Where(s => s.Services.Contains(searchString));

            }

            return View(await providers.ToListAsync());

        }

        public async Task<IActionResult> ListOfProvidersName(string searchString)
        {
            var providers = from m in _context.Providers
                            select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                providers = providers.Where(s => s.FirstName.Contains(searchString));

            }

            return View("ListOfProviders", await providers.ToListAsync());

        }

        // GET: Providers/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundId = _context.Consumers.Where(i => i.IdentityUserId == userId).SingleOrDefault();


            if (foundId == null)
            {
                RedirectToAction("Create");
            }

            var provider = await _context.Providers
                .Include(p => p.IdentityUser)
                .FirstOrDefaultAsync(m => m.ProviderId == id);
            
            if (provider == null)
            {
                return NotFound();
            }

            return View(provider);
        }

        // GET: Providers/Create
        public IActionResult Create()
        {

            return View();
        }

        // POST: Providers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Provider provider)
        {
            if (ModelState.IsValid)
            {
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                provider.IdentityUserId = userId;

                _context.Add(provider);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));

            }

            return View(provider);
        }

        // GET: Providers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var provider = await _context.Providers.FindAsync(id);
            if (provider == null)
            {
                return NotFound();
            }

            return View(provider);
        }

        // POST: Providers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Provider provider)
        {
            if (id != provider.ProviderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                    provider.IdentityUserId = userId;

                    _context.Update(provider);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProviderExists(provider.ProviderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(provider);
        }

        // GET: Providers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var provider = await _context.Providers
                .Include(p => p.IdentityUser)
                .FirstOrDefaultAsync(m => m.ProviderId == id);
            if (provider == null)
            {
                return NotFound();
            }

            return View(provider);
        }

        // POST: Providers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var provider = await _context.Providers.FindAsync(id);
            _context.Providers.Remove(provider);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Test()
        {
            return View();
        }

        public ActionResult Schedule(int? id)
        {

            var matchingProvider = _context.ProviderSchedule.Where(p => p.ProviderId == id);

            return View(matchingProvider);
        }

        public ActionResult ConsumerDetails(int? id)
        {
            var order = _context.Orders.Where(o => o.OrderId == id).SingleOrDefault();
            var foundConsumer = _context.Consumers.Where(c => c.ConsumerId == order.ConsumerId).SingleOrDefault();
            
            return View(foundConsumer);
        }

        private bool ProviderExists(int id)
        {
            return _context.Providers.Any(e => e.ProviderId == id);
        }
    }
}

SoloCapstoneProject/Views/Providers/ConsumerDetails.cshtml
@model SoloCapstoneProject.Models.Consumer

@{
    ViewData["Title"] = "ConsumerList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Location</h1>

<head>
    <style>

        #map {
            height: 450px; /* The height is 400 pixels */
            width: 50%; /* The width is the width of the web page */
            float: right;
            width: 50%;
        }


        .row:after {
            content: "";
            display: table;
            clear: both;
        }
    </style>
</head>

<body>
    <div id="map">
        <script>

        var marker;

        function initMap() {

            var defaultMap = { lat: @Model.Latitude, lng: @Model.Longitude };

            var map = new google.maps.Map(
                document.getElementById('map'), { zoom: 15, center: defaultMap });

            marker = new google.maps.Marker({ position: defaultMap, map: map });
        }
        </script>

        <script defer
                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAMsdaoeePqO9F_hpJsr3xJSPbPfF7dW0U&callback=initMap">
        </script>
    </div>

    </body>


<div class="card bg-secondary mb-3" style="max-width: 40rem;">
    <div class="card-header">Consumer Details</div>
    <div class="card-body">
        <h4 class="card-title">Consumer Profile</h4>
        <p class="card-text">

            <div>
                <h4>Consumer</h4>
                <hr />
                <div class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.FirstName)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.FirstName)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.LastName)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.LastName)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.PhoneNumber)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.PhoneNumber)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Address)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Address)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.City)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.City)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.State)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.State)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Zipcode)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Zipcode)
                    </dd>
                    </dl>
                </div>
                <div>
                    <a asp-action="Edit" asp-route-id="@Model.ConsumerId">Edit</a> |
                    <a asp-action="Index">Back to List</a>
                </div>

SoloCapstoneProject/Views/Providers/Create.cshtml
@model SoloCapstoneProject.Models.Provider

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Provider</h4>
<hr />

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<input type="hidden" asp-for="IdentityUserId" />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zipcode" class="control-label"></label>
                <input asp-for="Zipcode" class="form-control" />
                <span asp-validation-for="Zipcode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Services" class="control-label"></label>
                <input asp-for="Services" class="form-control" />
                <span asp-validation-for="Services" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SoloCapstoneProject/Views/Providers/Dashboard.cshtml
@model SoloCapstoneProject.Models.Provider

@{
    ViewData["Title"] = "Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Dashboard</h1>

<input type="hidden" asp-for="IdentityUserId" />

<div class="card bg-secondary mb-3" style="max-width: 40rem;">
    <div class="card-header">Provider Details</div>
    <div class="card-body">
        <h4 class="card-title">Provider Profile</h4>
        <p class="card-text">

            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.FirstName)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.FirstName)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.LastName)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.LastName)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Address)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Address)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.City)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.City)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.State)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.State)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Zipcode)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Zipcode)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Services)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Services)
                </dd>

            </dl>


        </p>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ProviderId">Edit</a> |
    <a asp-action="Delete" asp-route-id="@Model.ProviderId">Delete</a> |
    <a asp-action="Schedule" asp-route-id="@Model.ProviderId">My Schedule</a> |
    <a asp-action="ProviderRequest" asp-controller="Orders"
       asp-route-id="@Model.ProviderId">My Service Requests</a>
</div>

SoloCapstoneProject/Views/Providers/Delete.cshtml
@model SoloCapstoneProject.Models.Provider

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Provider</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zipcode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zipcode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Services)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Services)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdentityUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdentityUser.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProviderId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SoloCapstoneProject/Views/Providers/ListOfProviders.cshtml
@model IEnumerable<SoloCapstoneProject.Models.Provider>

@{
    ViewData["Title"] = "ListOfProviders";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>List Of Service Providers</h1>

<form asp-controller="Providers" asp-action="ListOfProviders">
    <p>
        Search A Service: <input type="text" name="SearchString">
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.FirstName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.LastName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Address)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.City)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.State)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Zipcode)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Services)
                    </th>

                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {

                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Address)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.City)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.State)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Zipcode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Services)
                    </td>

                    <td>
                        <a asp-action="Details" asp-route-id="@item.ProviderId">Request service</a>

                    </td>
                </tr>
                            }
                </tbody>
</table>

SoloCapstoneProject/Views/Providers/Schedule.cshtml
@model IEnumerable<SoloCapstoneProject.Models.ProviderSchedule>

@{
    ViewData["Title"] = "Schedule";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>

</head>

<h1>Schedule</h1>

    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.WeekDay)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OpeningHour)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ClosingHour)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.isAvailable)
                </th>

                <th></th>
            </tr>

        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.WeekDay)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.OpeningHour)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ClosingHour)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.isAvailable)
                    </td>
                
                <td>
                    <a asp-action="Create" asp-controller="Orders" asp-route-id="@item.ProviderId">Book an Appointment</a>
                </td>
                    </tr>
            }
        </tbody>
    </table>