SoloCapstoneProject/Models/Consumer.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SoloCapstoneProject.Models
{
    public class Consumer
    {

        [Key]
        public int ConsumerId { get; set; }
        [DisplayName("First Name")]
        public string FirstName { get; set; }
        [DisplayName("Last Name")]
        public string LastName { get; set; }
        public string Email { get; set; }

        [DisplayName("Contact Number")]
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }

        [ForeignKey("IdentityUser")]
        [DisplayName("User Id")]
        public string IdentityUserId { get; set; }
        public IdentityUser IdentityUser { get; set; }


    }
}

SoloCapstoneProject/Models/Consumers.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SoloCapstoneProject.Models
{
    public class Consumers
    {

        [Key]
        public int ConsumerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Zipcode { get; set; }

        [ForeignKey("IdentityUser")]
        public string IdentityUserId { get; set; }
        public IdentityUser IdentityUser { get; set; }


    }
}

SoloCapstoneProject/Controllers/ConsumersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SoloCapstoneProject.Contracts;
using SoloCapstoneProject.Data;
using SoloCapstoneProject.Models;
using SoloCapstoneProject.Services;
using Korzh.EasyQuery.Linq;

namespace SoloCapstoneProject.Controllers
{
    public class ConsumersController : Controller
    {
        
        private readonly ApplicationDbContext _context;
        private IRepositoryWrapper _repo;
        private readonly GeocodingService _geocodingService;

        public ConsumersController(ApplicationDbContext context, IRepositoryWrapper repo, GeocodingService geocodingService)
        {
            _context = context;
            _repo = repo;
            _geocodingService = geocodingService;
        }

        [Authorize(Roles = "Consumer")]

        // GET: Consumers
        public async Task<IActionResult> Index()
        {

            return RedirectToAction("Details");

        }

        // GET: Consumers/Details/5
        public async Task<IActionResult> Details()
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundId = _context.Consumers.Where(i => i.IdentityUserId == userId).SingleOrDefault();

            if (foundId == null)
            {
                return RedirectToAction("Create");
            }

            return View(foundId);
        }

        // GET: Consumers/Create
        public IActionResult Create()
        {

            return View();
        }

        // POST: Consumers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Consumer consumer)
        {

            if (ModelState.IsValid)
            {

                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                consumer.IdentityUserId = userId;

                var consumerWithLogLat = await _geocodingService.GetGeoCoding(consumer);

                _context.Add(consumerWithLogLat);
                _repo.Save();
                return RedirectToAction(nameof(Index));
            }
            
            return View("details", consumer);
        }

        // GET: Consumers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var consumer = await _context.Consumers.FindAsync(id);
            
            if (consumer == null)
            {
                return NotFound();
            }

            return View(consumer);
        }

        // POST: Consumers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Consumer consumer)
        {
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            consumer.IdentityUserId = userId;

            var consumerWithLogLat = await _geocodingService.GetGeoCoding(consumer);

            if (id != consumer.ConsumerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(consumer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ConsumerExists(consumer.ConsumerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("details", consumerWithLogLat);
            }

            return View(consumer);
        }

        // GET: Consumers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var consumer = await _context.Consumers
                .Include(c => c.IdentityUser)
                .FirstOrDefaultAsync(m => m.ConsumerId == id);
            if (consumer == null)
            {
                return NotFound();
            }

            return View(consumer);
        }

        // POST: Consumers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var consumer = await _context.Consumers.FindAsync(id);
            _context.Consumers.Remove(consumer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //Consumers/ConsumerList
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ConsumerList()
        {
            var applicationDbContext = _context.Consumers.Include(c => c.IdentityUser);

            
            return View(await applicationDbContext.ToListAsync());

        }

        private bool ConsumerExists(int id)
        {
            return _context.Consumers.Any(e => e.ConsumerId == id);
        }
    }
}

SoloCapstoneProject/Controllers/ProvidersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SoloCapstoneProject.Contracts;
using SoloCapstoneProject.Data;
using SoloCapstoneProject.Models;
using SoloCapstoneProject.Services;

namespace SoloCapstoneProject.Controllers
{
    public class ProvidersController : Controller
    {
        private readonly ApplicationDbContext _context;
        private IRepositoryWrapper _repo;

        public ProvidersController(ApplicationDbContext context, IRepositoryWrapper repo)
        {
            _context = context;
            _repo = repo;
        }

        [Authorize(Roles = "Provider")]

        // GET: Providers
        public async Task<IActionResult> Index()
        {

            return RedirectToAction("Dashboard");
        }

        public async Task<IActionResult> Dashboard(int? id)
        {

            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundProvider = _context.Providers.Where(i => i.IdentityUserId == userId).SingleOrDefault();


            if (foundProvider == null)
            {
                return RedirectToAction("Create");
            }

            return View(foundProvider);
        }


        public async Task<IActionResult> ListOfProviders(string searchString)
        {
            var providers = from m in _context.Providers
                            select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                providers = providers.Where(s => s.Services.Contains(searchString));

            }

            return View(await providers.ToListAsync());

        }

        public async Task<IActionResult> ListOfProvidersName(string searchString)
        {
            var providers = from m in _context.Providers
                            select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                providers = providers.Where(s => s.FirstName.Contains(searchString));

            }

            return View("ListOfProviders", await providers.ToListAsync());

        }

        // GET: Providers/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var foundId = _context.Consumers.Where(i => i.IdentityUserId == userId).SingleOrDefault();


            if (foundId == null)
            {
                RedirectToAction("Create");
            }

            var provider = await _context.Providers
                .Include(p => p.IdentityUser)
                .FirstOrDefaultAsync(m => m.ProviderId == id);
            
            if (provider == null)
            {
                return NotFound();
            }

            return View(provider);
        }

        // GET: Providers/Create
        public IActionResult Create()
        {

            return View();
        }

        // POST: Providers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Provider provider)
        {
            if (ModelState.IsValid)
            {
                var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                provider.IdentityUserId = userId;

                _context.Add(provider);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));

            }

            return View(provider);
        }

        // GET: Providers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var provider = await _context.Providers.FindAsync(id);
            if (provider == null)
            {
                return NotFound();
            }

            return View(provider);
        }

        // POST: Providers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Provider provider)
        {
            if (id != provider.ProviderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                    provider.IdentityUserId = userId;

                    _context.Update(provider);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProviderExists(provider.ProviderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            return View(provider);
        }

        // GET: Providers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var provider = await _context.Providers
                .Include(p => p.IdentityUser)
                .FirstOrDefaultAsync(m => m.ProviderId == id);
            if (provider == null)
            {
                return NotFound();
            }

            return View(provider);
        }

        // POST: Providers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var provider = await _context.Providers.FindAsync(id);
            _context.Providers.Remove(provider);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public ActionResult Test()
        {
            return View();
        }

        public ActionResult Schedule(int? id)
        {

            var matchingProvider = _context.ProviderSchedule.Where(p => p.ProviderId == id);

            return View(matchingProvider);
        }

        public ActionResult ConsumerDetails(int? id)
        {
            var order = _context.Orders.Where(o => o.OrderId == id).SingleOrDefault();
            var foundConsumer = _context.Consumers.Where(c => c.ConsumerId == order.ConsumerId).SingleOrDefault();
            
            return View(foundConsumer);
        }

        private bool ProviderExists(int id)
        {
            return _context.Providers.Any(e => e.ProviderId == id);
        }
    }
}

SoloCapstoneProject/Views/Consumers/ConsumerList.cshtml
@model IEnumerable<SoloCapstoneProject.Models.Consumer>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Zipcode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdentityUser)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Zipcode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdentityUser.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ConsumerId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ConsumerId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ConsumerId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

SoloCapstoneProject/Views/Consumers/Create.cshtml
@model SoloCapstoneProject.Models.Consumer

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Consumer</h4>
<hr />

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<input type="hidden" asp-for="IdentityUserId" />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zipcode" class="control-label"></label>
                <input asp-for="Zipcode" class="form-control" />
                <span asp-validation-for="Zipcode" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SoloCapstoneProject/Views/Consumers/Delete.cshtml
@model SoloCapstoneProject.Models.Consumer

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Consumer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zipcode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zipcode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdentityUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdentityUser.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ConsumerId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SoloCapstoneProject/Views/Consumers/Details.cshtml
@model SoloCapstoneProject.Models.Consumer

@{
    ViewData["Title"] = "ConsumerList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Location</h1>


<head>
    <style>

        #map {
            height: 300px; /* The height is 400 pixels */
            width: 50%; /* The width is the width of the web page */
            float: right;
            width: 50%;
        }


        .row:after {
            content: "";
            display: table;
            clear: both;
        }

    </style>
</head>

<body>
    <div id="map">
        <script>

        var marker;

        function initMap() {

            var defaultMap = { lat: @Model.Latitude, lng: @Model.Longitude };

            var map = new google.maps.Map(
                document.getElementById('map'), { zoom: 15, center: defaultMap });

            marker = new google.maps.Marker({ position: defaultMap, map: map });
        }
        </script>

        <script defer
                src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAMsdaoeePqO9F_hpJsr3xJSPbPfF7dW0U&callback=initMap">
        </script>
    </div>


    <div class="card bg-secondary mb-3" style="max-width: 40rem;">
        <div class="card-header">Consumer Details</div>
        <div class="card-body">
            <h4 class="card-title">Consumer Profile</h4>
            <p class="card-text">

                    <h4>Consumer</h4>
                    <hr />
                    <div class="row">
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.FirstName)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.FirstName)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.LastName)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.LastName)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Address)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Address)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.City)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.City)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.State)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.State)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Zipcode)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Zipcode)
                        </dd>
                        </dl>
                    </div>
                </div>
        </div>

                    <div>
                        <a asp-action="Edit" asp-route-id="@Model.ConsumerId">Edit</a> |
                        <a asp-action="Delete" asp-route-id="@Model.ConsumerId">Delete</a>

                    </div>

</body>

SoloCapstoneProject/Views/Consumers/Edit.cshtml
@model SoloCapstoneProject.Models.Consumer

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Consumer</h4>
<hr />

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<input type="hidden" asp-for="IdentityUserId" />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ConsumerId" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zipcode" class="control-label"></label>
                <input asp-for="Zipcode" class="form-control" />
                <span asp-validation-for="Zipcode" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SoloCapstoneProject/Views/Consumers/Index.cshtml
@model IEnumerable<SoloCapstoneProject.Models.Consumer>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Zipcode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdentityUser)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Zipcode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdentityUser.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ConsumerId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ConsumerId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ConsumerId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

SoloCapstoneProject/Views/Consumers/ProviderList.cshtml
@model IEnumerable<SoloCapstoneProject.Models.Provider>

@{
    ViewData["Title"] = "ProviderList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Service Providers</h1>


<form asp-controller="Consumers" asp-action="ProviderList">
    <p>
        Search A Service: <input type="text" name="SearchString">
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Zipcode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Services)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Zipcode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Services)
            </td>
            <td>
                @*<a asp-controller="Providers"
                   asp-action="Details" asp-route-id="@Model.consumerId">Schedule an Appointment</a>*@
            </td>
        </tr>
}
    </tbody>
</table>